README.md
pom.xml

Updated Project URL and add Developer and SCM information as requested for Jenkins update center hosting.

Update Project URL, Add Developer and SCM information

---

Jenkinsfile
pom.xml

* Use Jenkins build number as patch number
* Release plugin when building on master

Continuous Delivery for Sonatype Jenkins Instance

---

Jenkinsfile

* Exclude Jenkins Test Harness from Policy Evaluation
* Don't push tags until after staging repository is released

Continuous Delivery Fixes

---

Jenkinsfile
pom.xml

Nexus Jenkins plugin fails to close HTTP connections when uploading to Nexus
https://issues.sonatype.org/browse/INT-195
https://jenkins.zion.aws.s/job/integrations/job/nexus-platform-plugin/9/

Close HTTP connections after uploading to Nexus Repository

---

pom.xml

https://issues.sonatype.org/browse/INT-297
https://jenkins.zion.aws.s/job/integrations/job/nexus-platform-plugin-feature/job/INT-297_add_docker_support/1

INT-297 Upgrade to nexus-platform-api-1.6 to add support for docker

---

pom.xml

Updates to latest java-nexus-api 1.7
Fixes: https://issues.sonatype.org/browse/INT-372
Tested using ATH for Jenkins 2.60.2-lts and 2.73.1-lts
Jenkins: https://jenkins.zion.aws.s/job/integrations/job/nexus-platform-plugin-feature/job/INT-release-1.7/

INT-release_1.7

---

Jenkinsfile

- Use withGpgCredentials for code signing.
- Explicitly build on slave node.

INT - Use withGpgCredentials

---

pom.xml
src/test/java/org/sonatype/nexus/ci/config/ComToOrgMigratorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthActionTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyFailureMessageFormatterTest.groovy

INT-448 Jenkins updates for transitive dependency changes pulled in through Nexus Java API
https://issues.sonatype.org/browse/INT-448

INT-448 Updates for Java API Bump

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy

https://issues.sonatype.org/browse/INT-420

INT-422 Base directory support in Jenkins.

---

src/main/java/org/sonatype/nexus/ci/config/NxiqConfiguration.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluator.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptor.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep.groovy
src/main/java/org/sonatype/nexus/ci/iq/ModuleExclude.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteScannerFactory.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/help-iqModuleExcludes.html
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep/help-iqModuleExcludes.html
src/main/resources/org/sonatype/nexus/ci/iq/Messages.properties
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy

https://issues.sonatype.org/browse/INT-424
https://youtu.be/OtJm-kvgzuA

INT-424 Module XML Support in Jenkins

---

pom.xml
src/main/java/org/sonatype/nexus/ci/config/NxiqConfiguration.groovy
src/main/java/org/sonatype/nexus/ci/config/Nxrm2Configuration.groovy
src/main/java/org/sonatype/nexus/ci/util/FormUtil.groovy
src/test/java/org/sonatype/nexus/ci/config/Nxrm2ConfigurationTest.groovy
src/test/java/org/sonatype/nexus/ci/util/FormUtilIntegrationTest.groovy

https://issues.sonatype.org/browse/INT-441
https://youtu.be/0rRv536itjo
- Show credentials at project level to those with permissions to configure project and see credentials.

INT-441 Show Credentials Permissions

---

src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluationException.groovy
src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluatorExecution.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy

https://issues.sonatype.org/browse/INT-451
https://youtu.be/BjSL4xNWaN4

INT-451 Fail pipeline with policy action.

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy

https://issues.sonatype.org/browse/INT-431
https://youtu.be/U9K24bwfc3k

INT-431 Declarative pipeline support.

---

Jenkinsfile

Upgraded to the new c-i-pipeline-library.

INT - Change to ci-pipeline-library

---

pom.xml

https://issues.sonatype.org/browse/CLM-10103
https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/Update_Nexus_Java_API_Auto_App_Error_Message/

Update the version of nexus-java-api with auto app error message CLM-10118 CLM-10103

---

pom.xml

Upgrade to the latest version of the nexus-platform-api.
https://issues.sonatype.org/browse/CLM-10234
https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/nexus-platform-plugin-feature/job/CLM-10234

CLM-10234 - Upgrade to the latest nexus platform api

---

src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluator.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep.groovy

Upstream version of: https://github.com/sonatype/jenkins-nexus-platform-plugin/pull/38

Fix Jenkins Nexus plugin module excludes advance option input CLM-11010

---

src/main/java/org/sonatype/nexus/ci/config/Nxrm3Configuration.groovy
src/test/java/org/sonatype/nexus/ci/config/Nxrm3ConfigurationTest.groovy

Jenkins Platform Plugin unable to determine Nexus Repository Manager version using Server URL with trailing slash

---

pom.xml

Bump to 3.3.20181025-095610.1ce86a (upstream for sonatype#39)

Bump to latest nexus-java-api

---

Jenkinsfile.releaseInsightJiraVersion

https://issues.sonatype.org/browse/CLM-11254

Added jenkins build to release the current Insight Jira version and add a new jenkins-next version CLM-11254

---

pom.xml

Story: https://issues.sonatype.org/browse/CLM-11968
Task: https://issues.sonatype.org/browse/CLM-11969
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/CLM-11969/
To include insight-scanner:2.11.1 which includes python wheel (.whl) package recognition support

Upgraded to nexus-pltform-api:3.4.20181205-180005.1567c7b - CLM-11969

---

pom.xml
src/test/java/org/sonatype/nexus/ci/config/ComToOrgMigratorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqApplicationMigratorIntegrationTest.groovy

Bug: https://issues.sonatype.org/browse/CLM-12178
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/copy_config_before_migrate/lastBuild

Upgrade spock-core to 1.2-groovy-2.4 and ensure config is ready before migration test - CLM-12178

---

src/main/java/org/sonatype/nexus/ci/nxrm/v3/AssociateTagStep.java
src/main/java/org/sonatype/nexus/ci/nxrm/v3/ComponentUploaderNxrm3.groovy
src/main/java/org/sonatype/nexus/ci/nxrm/v3/CreateTagStep.java
src/main/java/org/sonatype/nexus/ci/nxrm/v3/DeleteComponentsStep.java
src/main/java/org/sonatype/nexus/ci/nxrm/v3/MoveComponentsStep.java
src/test/java/org/sonatype/nexus/ci/nxrm/ComponentUploaderNxrm3Test.groovy
src/test/java/org/sonatype/nexus/ci/nxrm/v3/AssociateTagStepTest.groovy
src/test/java/org/sonatype/nexus/ci/nxrm/v3/CreateTagStepTest.groovy
src/test/java/org/sonatype/nexus/ci/nxrm/v3/DeleteComponentsStepTest.groovy
src/test/java/org/sonatype/nexus/ci/nxrm/v3/MoveComponentsStepTest.groovy

https://issues.sonatype.org/browse/INT-1537
Resolve environment variables in Jenkins freestyle steps for the NXRM tag field

INT-1537 expand tag name

---

src/main/java/org/sonatype/nexus/ci/nxrm/v3/ComponentUploaderNxrm3.groovy

https://issues.sonatype.org/browse/INT-1537
Follow up to #74, additionally fixes for logging

Resolve environment variables in tag logging - INT-1537

---

src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluator.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptor.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteScannerFactory.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/help-advancedProperties.html
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep/help-advancedProperties.html
src/main/resources/org/sonatype/nexus/ci/iq/Messages.properties
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy

Add an "Advanced properties" text area which provides support for "key=value" properties to be entered and passed along to the IQ Scanner.

Add custom/advanced properties to iq scanner

---

pom.xml

Story: https://issues.sonatype.org/browse/CLM-12408
Task: https://issues.sonatype.org/browse/CLM-12430
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/upgrade_findbugs/lastBuild

Upgrade parent org.jenkins-ci.plugins:plugin to 3.35 - CLM-12408 CLM-12430

---

pom.xml

Story: https://issues.sonatype.org/browse/CLM-12331
Jenkins: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/CLM-12331_4/

Upgrade to latest nexus-platform-api for golang scanning support - CLM-12331

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy

https://issues.sonatype.org/browse/CLM-12558
https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/CLM-12558_add_polling/
Adding polling for policy evaluations.

Add polling - CLM-12588

---

README.md

In preparation for https://jenkins.io/blog/2019/10/21/plugin-docs-on-github/

Move plugin overview from Jenkins wiki to GitHub README

---

README.md

**Description:** Update change log entries for the latest release

Update change log entries for 3.8.20191204-084645.a4bff16

---

pom.xml
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy

- provide a profile for working supported environment and minor test changes to accommodate string syntax changes in certain error messages

INT-2151 - CI Improvements:  Nexus Platform Plugin

---

src/main/resources/META-INF/hudson.remoting.ClassFilter
src/test/java/org/sonatype/nexus/ci/config/ComToOrgMigratorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/ClassFilterLoggingTestTrait.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy

Add a trait that can be added to tests to try to get coverage on any JEP-200 that might come up in the future
Upstream: https://issues.sonatype.org/browse/INT-2451

Create test to cover JEP-200

---

pom.xml

https://issues.sonatype.org/browse/CLM-15620

Configured nexus-staging-maven-plugin to automatically release staging repository once successfully closed CLM-15620

---

pom.xml

Adds support to scan go.list files.

CLM-16267 Upgrade nexus-platform-api to 3.16

---

pom.xml

Adds support for scanning conaninfo.txt files for Conan projects.

Upgrade nexus-platform-api to 3.17

---

Jenkinsfile.sonatype

**Description:** Update build config to do feature branch policy evaluations to enable PR commenting.
**Links:**
**Jira:** https://issues.sonatype.org/browse/INT-2910
**Build:** https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/nexus-platform-plugin-feature/job/INT-2910_add_feature_branch_policy_evals/

INT-2910 add feature branch policy evals

---

pom.xml

The purpose of this PR is to modify the Nexus Platform Plugin for Jenkins to support terraform plans (i.e. update java-api to the latest version).
Jira: https://issues.sonatype.org/browse/INT-4160
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-4160-update-java-api-version/

INT-4160 - Update java-api to 3.25

---

src/main/java/org/sonatype/nexus/ci/config/ComToOrgMigrator.groovy
src/main/java/org/sonatype/nexus/ci/config/NxiqConfiguration.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/resources/org/sonatype/nexus/ci/config/Messages.properties
src/main/resources/org/sonatype/nexus/ci/config/NxiqConfiguration/config.groovy
src/main/resources/org/sonatype/nexus/ci/config/NxiqConfiguration/help-hideReports.html
src/test/java/org/sonatype/nexus/ci/config/GlobalNexusConfigurationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqClientFactoryTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/util/IqUtilTest.groovy

https://issues.sonatype.org/browse/INT-4419

INT-4419 - Add an option to hide reports info in the Jenkins plugin

---

pom.xml

JIRA: https://issues.sonatype.org/browse/CLM-17769
JENKINS: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/UpdateJavaApi/

Updated nexus-platform-api>3.28

---

src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqServerMockUtility.groovy
src/test/java/org/sonatype/nexus/ci/iq/PipelineSyntaxIntegrationTest.groovy

Enhance functional testing of the pipeline syntax page, which relies on ajax requests to a configured server to function correctly.
- [X ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [X ] Ensure that the pull request title represents the desired changelog entry
- [X ] Please describe what you did
- [X ] Link to relevant issues in GitHub or Jira
- [X ] Link to relevant pull requests, esp. upstream and downstream changes
- [ X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

INT-4616 test pipeline syntax page

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteScannerFactory.groovy
src/test/java/org/sonatype/nexus/ci/config/ComToOrgMigratorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqServerMockUtility.groovy

Send the Nexus IQ licensed features into the scanner to filter IaC content
Jira: https://issues.sonatype.org/browse/INT-4805

INT-4805 Send licensed features into the scanner

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy

Add nexus container analysis support to the nexus-platform-plugin.
Jira: https://issues.sonatype.org/browse/INTC-183
Jenkins: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INTC-183-container-for-jenkins/

INTC-183 Add support for nexus container analysis

---

pom.xml

https://issues.sonatype.org/browse/INTC-243
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INTC-243-Bump_Platform_Api_Version/
https://ci.jenkins.io/job/Plugins/job/nexus-platform-plugin/job/INTC-243-Bump_Platform_Api_Version/

INTC-243 - Bump nexus-platform-api.version

---

pom.xml

https://issues.sonatype.org/browse/INTC-204
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INTC-204_Incorporate_Container_Scanning_in_Jenkins/3/

INTC-204 - Incorporate Container Scanning in Jenkins

---

README.md

Story: https://issues.sonatype.org/browse/CLM-19563

Add release note for npm dependency information and InnerSource identification - CLM-19563

---

src/main/java/org/sonatype/nexus/ci/config/IqConfigNoIdToIdMigrator.groovy
src/main/java/org/sonatype/nexus/ci/config/NxiqConfiguration.groovy
src/main/java/org/sonatype/nexus/ci/util/IqUtil.groovy
src/main/resources/org/sonatype/nexus/ci/config/GlobalNexusConfiguration/config.groovy
src/main/resources/org/sonatype/nexus/ci/config/Messages.properties
src/main/resources/org/sonatype/nexus/ci/config/NxiqConfiguration/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction/summary.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationProjectAction/jobMain.groovy
src/test/java/org/sonatype/nexus/ci/config/IqConfigNoIdToIdMigratorTest.groovy
src/test/java/org/sonatype/nexus/ci/config/NxiqConfigurationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/util/IqUtilTest.groovy

https://issues.sonatype.org/browse/INT-6202
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6202_SmallFixes/

  Small fixes and more tests for multiple IQ server support CLM-19160 INT-6202

---

pom.xml

https://issues.sonatype.org/browse/INT-6277
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6277_RemoveTokenMacroDep/

Remove unnecessary dependency on org.jenkins-ci.plugins:token-macro INT-6276 INT-6277

---

pom.xml
src/test/java/org/sonatype/nexus/ci/iq/IqClientFactoryTest.groovy

https://issues.sonatype.org/browse/INT-6201
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/MinJenkinsVersion/

Updated the min Jenkins version required to 2.249.1 INT-6201

---

Jenkinsfile.sonatype.release

Automatically release the Jira fix version at the end of the release CI job.
JIRA: https://issues.sonatype.org/browse/INT-6578
Build: N/A

Release Jira fix version with every release - INT-6578

---

Jenkinsfile.sonatype.release

Jira: https://issues.sonatype.org/browse/INT-6611
Build: N/A

Automatically verify download links - INT-6611

---

pom.xml

Bump innersource dependencies for `nexus-platform-plugin`.
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/bump-innersource-dependencies-6022c8/

Bump innersource dependencies

---

docs/overview.md
pom.xml

Continuation of https://github.com/sonatype/nexus-java-api/pull/198
Jira: https://issues.sonatype.org/browse/INT-6669
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6669_fix_for_NoSuchMethodError/

Fix class not found issue - INT-6669

---

pom.xml

Jira: https://issues.sonatype.org/browse/INT-6682
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6682_fix_IllegalAccess_for_org.objectweb.asm/

Fix IllegalAccess errors for org.objectweb.asm - INT-6682

---

src/main/java/org/sonatype/nexus/ci/nxrm/v3/AssociateTagStep.java
src/main/java/org/sonatype/nexus/ci/nxrm/v3/CreateTagStep.java
src/main/java/org/sonatype/nexus/ci/nxrm/v3/DeleteComponentsStep.java
src/main/java/org/sonatype/nexus/ci/nxrm/v3/MoveComponentsStep.java
src/test/java/org/sonatype/nexus/ci/nxrm/v3/AssociateTagStepTest.groovy

This PR adds support for environment variables in search criteria, associate tag step, for both keys and values. 
Jira: https://issues.sonatype.org/browse/INT-2645
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-2645_Env_Variables_in_Search_Criteria/

Support env variables in search criteria - associate tag step - INT-2645

---

Jenkinsfile.sonatype.extra-tests
pom.xml
src/test/resources/org/sonatype/nexus/ci/quality/RuleSetAll.groovy

Use plugin bill of materials for easier dependency management and upgrade some other dependencies.
References: 
- https://github.com/jenkinsci/bom#bill-of-materials-for-jenkins-plugins
- https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#
Jira: https://issues.sonatype.org/browse/INT-6825
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6825-pom_file_cleanup/

Project configuration modernization - INT-6825

---

pom.xml

Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/iday-fix-ide-test-run/

Fix the unit test running in IDEA

---

Jenkinsfile.sonatype.extra-tests

Jira: https://issues.sonatype.org/browse/INT-7072
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7072_Check_compatibility_with_2.346.3/

Check compatibility with Jenkins version 2.346.3

---

pom.xml

Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/iday-pom.xml-cleanup/

Some version bump ups and more cleanup (i-day)

---

README.md
docs/overview.md
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationReportAction/index.jelly

Updating integrations help pages links
JIRA: https://issues.sonatype.org/browse/INT-7283
Build: N/A

INT-7283 Updating integrations help pages links

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluatorExecution.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy

Making the stage unstable for Jenkins and Blue Ocean graphs
JIRA: https://issues.sonatype.org/browse/INT-7293
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7293-making-stage-unstable/
- Jenkins Graph
- Blue Ocean Graph

INT-7293 Making stage unstable for Jenkins and Blue Ocean graphs

---

Jenkinsfile.sonatype.extra-tests

Jira: https://issues.sonatype.org/browse/INT-7370
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7370_Check_compatibility_with_Jenkins_2.361.2/

Check compatibility with Jenkins version 2.361.2 - INT-7370

---

Jenkinsfile.sonatype.extra-tests

Jira: https://issues.sonatype.org/browse/INT-7454
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7454_Check_compatibility_with_Jenkins_2.361.3/

Check compatibility with Jenkins version 2.361.3 - INT-7454

---

pom.xml

Bump up buildsupport and maven plugin versions.
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/bump_up_buildsupport_and_maven_plugin_versions/

Boyscout: Bump up buildsupport and maven plugin versions

---

pom.xml

https://issues.sonatype.org/browse/CLM-23219
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-23219-Bump_nexus-platform-api_version/

CLM-23219 - Bump nexus-platform-plugin version

---

Jenkinsfile.sonatype.extra-tests

Jira: https://issues.sonatype.org/browse/INT-7538
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7538_Check_compatibility_with_Jenkins_2.375.1/2/

Check compatibility with jenkins 2.375.1 - INT-7538

---

src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy

Removing support for IAC scanning
JIRA: https://issues.sonatype.org/browse/INT-7518
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7518-remove-support-for-iac-scanning/

INT-7518 Removing support for IAC scanning

---

Jenkinsfile
Jenkinsfile.sonatype.extra-tests

Jira: https://issues.sonatype.org/browse/CLM-24758
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-24758_Check_compatibility_with_2.387.1/

Check compatibility with Jenkins version 2.387.1 - CLM-24758

---

src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluator.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptor.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/help-failBuildOnScanningErrors.html
src/main/resources/org/sonatype/nexus/ci/iq/Messages.properties
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/resources/org/sonatype/nexus/ci/quality/RuleSetAll.groovy

https://sonatype.atlassian.net/browse/CLM-25824
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-25824_Jenkins_Add_a_flag_to_fail_on_scanning_errors/

CLM-25824 - Jenkins: Add a flag to fail on scanning errors

---

Jenkinsfile.sonatype.extra-tests

Jira: https://sonatype.atlassian.net/browse/CLM-26139
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/extra-tests/job/CLM-26139_Check_Jenkins_Compatability_2.401.1/

Checking Jenkins Compatability with version 2.401.1

---

pom.xml

Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/bump-innersource-dependencies-803f2b/

Bump innersource dependencies - IQ 164

---

README.md
docs/overview.md
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationReportAction/index.jelly
src/main/resources/org/sonatype/nexus/ci/nxrm/v3/AssociateTagStep/help-search.html

Jira: https://sonatype.atlassian.net/browse/CLM-26312
Build: _not needed_

Ensure all links go through links-ng - CLM-26312

---

pom.xml

https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/bump_nexus-platform-api_version/

Bump nexus-platform-api version

---

pom.xml

Jira: https://sonatype.atlassian.net/browse/CLM-26859
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-26859_Use_proper_asm_library/

Use proper asm dependency - CLM-26859

---

Jenkinsfile.sonatype.extra-tests
pom.xml
src/test/java/org/sonatype/nexus/ci/iq/IqClientFactoryTest.groovy

Jira: N/A
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/minimum_jenkins_version_to_2.346.3/

I-day: Minimum jenkins version is 2.346.3 and it runs with Java 17

---

src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction.groovy
src/main/resources/org/sonatype/nexus/ci/iq/Messages.properties
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction/summary.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationProjectAction/jobMain.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqServerMockUtility.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthActionTest.groovy

Jira: https://sonatype.atlassian.net/browse/CLM-27365
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-27365_introduce_legacy_violations/

Introduce the new term Legacy Violations - CLM-27365

---

src/main/webapp/features/iq/charting/styles.css

https://sonatype.atlassian.net/browse/CLM-27391
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-27391-Dark_Theme_Support_For_Eval_Chart/
Below are the screenshots from my local using this branch for light theme and dark theme.

CLM-27391 - Dark Theme Support For Eval Chart

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction.groovy

https://sonatype.atlassian.net/browse/CLM-27746
```[tasklist]
```

CLM-27746: Renamed Grandfathering Prop

---

Jenkinsfile.sonatype
pom.xml

Jira: https://sonatype.atlassian.net/browse/CLM-28108
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-28108-build-it-in-Sonatype-CI/

Build the plugin in Sonatype CI - CLM-28108

---

Jenkinsfile.sonatype.deploy

Jira: https://sonatype.atlassian.net/browse/CLM-28670
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-28670-paligo-update/

Perform Paligo updates - CLM-28670

---

pom.xml

Jira: https://sonatype.atlassian.net/browse/INT-7989
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/bump-innersource-dependencies-227e59/

Bump innersource dependencies - IQ 175

---

Jenkinsfile.sonatype.extra-tests
pom.xml

Check Jenkins plugin compatibility with Jenkins version 2.440.3
Jenkins build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-8058/
```[tasklist]
```

INT-8058 checking jenkins 2.440.3 compatibility
