src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy
src/test/java/org/sonatype/nexus/ci/util/IqUtilTest.groovy

- When mocking classes ensure their implementation is not expected from other tests
- Confine meta changes if implementation used elsewhere

ConfineMetaClassChanges for classes that are used in actual and mock form

---

pom.xml

Updated nexus-platform-api to 1.8.20171120-150856.6c36986 to include support for java 9 bytecode hashing.
https://issues.sonatype.org/browse/CLM-9174
Supersedes #14.

CLM-9174 Java 9 bytecode hashing support.

---

pom.xml
src/main/resources/META-INF/hudson.remoting.ClassFilter
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy

https://issues.jenkins-ci.org/browse/JENKINS-48940
[INTERNAL] https://issues.sonatype.org/browse/INT-418

 JENKINS-48940 INT-418 Add whitelist for serialized classes.

---

src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction/summary.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationProjectAction/jobMain.groovy
src/main/webapp/css/nexus.css

The css tag is not available in jenkins versions prior to 2.0. Allow the css to load for jenkins v1+ for policy violations on the job main and summary pages.
Tested with jenkins-1.642.18.1 and jenkins.2.107.3.
JIRA:   https://issues.sonatype.org/browse/INT-601
CI: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/nexus-platform-plugin-feature/job/INT-601-css-chiclets/2
https://youtu.be/A3q_t_tVc2c

INT-601 Correct CSS loading for Jenkins v1

---

src/main/java/org/sonatype/nexus/ci/nxrm/v3/MoveComponentsStep.java
src/test/java/org/sonatype/nexus/ci/nxrm/v3/MoveComponentsStepTest.groovy

https://issues.sonatype.org/browse/NEXUS-17660
https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/NEXUS-17660_promote_by_search/
Allows users to specify search parameters for the `moveComponents` step to allow finer grained filtering of components. This will allow tags that apply to multiple components spanning multiple formats to be manipulated without needing separate tags

NEXUS-17660: support move by search from pipeline

---

pom.xml

Jira: https://issues.sonatype.org/browse/INT-952
CI: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/INT-952-bump-groovy-all/

INT-952 Bump groovy-all to 2.4.15

---

Jenkinsfile.sonatype

Currently master branch will attempt a deploy which requires logic invoked when isRelease is true. If mavenSnapshotPipeline is used on master an unauthorized deploy will be attempted against the jenkinsci repository.

Prevent non release builds from master.

---

README.md

The current readme links to NXRM2 documentation and IQ documentation. There is also a link for NXRM3 that was missing. This will provide a link to all three.

Update readme to reflect all three documentation links

---

src/main/java/org/sonatype/nexus/ci/iq/SelectedApplication.java

When implementing the `manual` application ID the path to the descriptor backing the application ID changed. Therefore the binding to the `job credential` parameter broke (always empty string). When job credentials are not available the plugin falls back to the credentials configured in the global configuration, so this was not immediately noticed.
JIRA: https://issues.sonatype.org/browse/INT-554
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/nexus-platform-plugin-feature/job/INT-554_fix_application_dropdown_credentials/1/
The essential part in testing it is to set up the global IQ configuration with credentials that that job does not have access to. This fix now allows you to override these (inacessible) credentials with job specific credentials and can select the …

fix path to credential parameter

---

pom.xml
src/main/java/org/sonatype/nexus/ci/config/Nxrm3Configuration.groovy
src/main/java/org/sonatype/nexus/ci/util/RepositoryManagerClientUtil.groovy
src/test/java/org/sonatype/nexus/ci/config/Nxrm3ConfigurationTest.groovy
src/test/java/org/sonatype/nexus/ci/util/RepositoryManagerClientUtilTest.groovy

Took the work initially completed by Kris Wright and added tests.  Kris modified the plugin here to use the Java api which does use proxy configuration if it's present. 
This has a corresponding set of changes in the platform-plugin as well.
https://github.com/sonatype/nexus-java-api/pull/109
JIRA: https://issues.sonatype.org/browse/NEXUS-18262

Nexus-18262: use api for version test including tests

---

src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction.groovy
src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluationProjectAction.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationProjectAction/jobMain.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthActionTest.groovy

**Description:**
In the case of build pipelines with multiple nexusPolicyEvaluation invocations the results displayed on the job summary page had multiple entries for the same result.  In addition, on the job run page all of the report links pointed to the same report, which was for the first eval performed.  
This fix addresses both of those problems.
**Links**:
Jira: https://issues.sonatype.org/browse/INT-562
Jenkins:  ??
**Screencast**:
https://youtu.be/Aa4mU6iELS4

INT-562 fix policy eval result UI/links

---

src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction/summary.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationProjectAction/jobMain.groovy

Description:
The purpose of this change was to ensure that the policy report, when accessed by clicking the link in the build results in Jenkins, will open in a new browser window rather than replacing the Jenkins window.
Links:
Jira: https://issues.sonatype.org/browse/INT-1203
Screencast:
n/a

INT-1203 open policy eval links in new window

---

pom.xml

Story: https://issues.sonatype.org/browse/CLM-11662
Task: https://issues.sonatype.org/browse/CLM-11744
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/CLM-11744_update_api_java_10_11/lastBuild
Although the above build works I think the continuous-integration/jenkins build won't pass until the release from https://jenkins.zion.aws.s/job/integrations/job/java-api/job/nexus-java-api/87/ becomes available
Edit: It's available on https://repo1.maven.org/maven2/com/sonatype/nexus/nexus-platform-api/3.5.20190114-150153.a6e0a60/ (thanks Justin) the CI build below is not a concern

Added support for hashing Java 10/11 bytecode - CLM-11662 CLM-11744

---

pom.xml

https://issues.sonatype.org/browse/CLM-12124
Simple bump of the nexus-platform-api version to pick up newer fingerprinting with support for Java 12.

Fingerprinting for Java 12 bytecode

---

pom.xml
src/main/java/org/sonatype/nexus/ci/nxrm/MavenAsset.groovy
src/main/java/org/sonatype/nexus/ci/nxrm/MavenCoordinate.groovy
src/main/java/org/sonatype/nexus/ci/util/FormUtil.groovy

Story: https://issues.sonatype.org/browse/CLM-12408
Task: https://issues.sonatype.org/browse/CLM-12430
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/CLM-12430_openjdk_11_prep/lastBuild
Maybe counts as trivial but wasn't completely sure, maybe something I'm missing as well. This is essentially to allow us to only have to make Jenkinsfile/pom changes when configuring for Java 11

Upgrade groovy-eclipse-batch to 2.4.16-03 for Java 11 - CLM-12408 CLM-12430

---

pom.xml

Story: https://issues.sonatype.org/browse/CLM-12408
Task: https://issues.sonatype.org/browse/CLM-12430
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/CLM-12430_update_cglib/lastBuild

Upgrade cglib-nodep to 3.2.10 - CLM-12408 CLM-12430

---

pom.xml

Story: https://issues.sonatype.org/browse/CLM-12408
Task: https://issues.sonatype.org/browse/CLM-12430
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/CLM-12430_disable_javadoc/lastBuild

Disable unused javadoc maven plugin - CLM-12408 CLM-12430

---

pom.xml

The purpose of this PR is to bump the version of the nexus-java-api which provides some updates, to include updates to scanning

INT-1965 bump java api version

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/resources/org/sonatype/nexus/ci/iq/Messages.properties
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy

Problem: 
Nexus policy evaluation step fails with NPE if not in an agent/node context (see Jira like for details).
Fix: 
Nexus policy evaluation step check upfront if it runs in an agent/node context. If not it fails the build with an appropriate error message.
JIRA: https://issues.sonatype.org/browse/INT-1955
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/INT-1955-plugin-requires-agent/1/

INT-1955 - Fail with error message if not in agent/node context

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/test/java/org/sonatype/nexus/ci/config/ComToOrgMigratorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy

It was reported that a user running Nexus Platform Plugin 3.7.20190823-091836.9f85050 on a standalone Jenkins installation does not get commit status updates after the policy evaluation step is executed.
During investigation it was found that the commit hash is not determined, so no attempt to update the commit status is made.
**Solution**:
Make sure that JGitCommitHashFinder uses Jenkins' workspace directory as a starting point for the git directory lookup, instead of the current working directory (as it is now)
JIRA: https://issues.sonatype.org/browse/INT-2083
Build: https://jenkins.zion.aws.s/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/INT-2083-commit-hash-cannot-be-determined/5/

INT-2083 Commit hash cannot be determined

---

pom.xml

Jira: https://issues.sonatype.org/browse/CLM-14057
Bump up nexus-platform-api to 3.10.20191126-161807.6e95e4b which has third party scanning enabled (Clair and CycloneDX SBOM) from `insight-scanner`

Enable third party scanning

---

src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluationReportAction.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationReportAction/index.jelly

Jenkins Plugin Build Report - small style fixes
The Build Failure Report should be accessible from the build page in Jenkins, under a job. It should show up in the left hand navigation under Nexus IQ Policy Evaluation.
JIRA: https://issues.sonatype.org/browse/INTC-95
Build: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fnexus-platform-plugin/detail/PR-107/1/
https://youtu.be/DSoR_7dYRTA

INTC-95 Jenkins Plugin Build Report style fixes

---

README.md
pom.xml

Use [GitHub README](https://jenkins.io/blog/2019/10/21/plugin-docs-on-github/) instead of [Jenkins Wiki](https://wiki.jenkins.io/display/JENKINS/Nexus+Platform+Plugin)
JIRA: [INTC-132](https://issues.sonatype.org/browse/INTC-132)
Build: 
* [Downstream Jenkins Job](https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/intc-132-update-jenkins-to-use-github-readme-for-plugins-page/)
* [Upstream Jenkins Job](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fnexus-platform-plugin/detail/PR-106/1/pipeline)
N/A

INTC-132 Update missing changelog entries

---

src/main/webapp/features/iq/charting/iqChart.js

In the Jenkins -> Pipeline for "Trends for Nexus IQ Policy Evaluation" on the y-axis shows float values instead of integer ones.
JIRA: [INTC-136](https://issues.sonatype.org/browse/INTC-136)
Build: 
* [Downstream Jenkins Job](https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/sonatype-nexus-platform-plugin-feature/job/intc-136-jenkins-build-chart-shows-float-yaxis-values/)
See screens from the [ticket](https://issues.sonatype.org/browse/INTC-136?focusedCommentId=888109&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-888109)

INTC-136 Jenkins build chart shows float yaxis values

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/RemoteRepositoryUrlFinder.groovy

The commit hash and the repository URL finders use class-instantiated loggers to log relevant information. 
In Jenkins it is desirable that the discovery information ends up in the build log, rather than the system log. 
The purpose of this change is to pass down to those finders the build logger
JIRA: https://issues.sonatype.org/browse/INT-2484

Update nexus-java-api and pass down the build logger - INT-2484

---

pom.xml

Jira: https://issues.sonatype.org/browse/CLM-15068
Jenkins: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/nexus-platform-plugin-feature/job/enable_third_party_scans_default/
As a part of CLM-15068, we want to update the version of `nexus-platform-api` to the version enabling  scanning conanfile.txt (C++) / Gemfile.lock (RubyGems) / composer.lock (PHP) files by default.
Below are screen shot's of the jenkins plugin built from this branch, scanning the above mentioned scan files (enabled by default).
PHP  (composer)
Ruby (gemfile)
C++ (conan)

Enable Conan, Composer and Gemfile manifest scanning

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction.groovy
src/main/java/org/sonatype/nexus/ci/iq/PolicyFailureMessageFormatter.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction/summary.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationProjectAction/jobMain.groovy
src/test/java/org/sonatype/nexus/ci/config/ComToOrgMigratorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthActionTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyEvaluationReportActionTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyFailureMessageFormatterTest.groovy

The purpose of this change is to use policy violation counts in the violation summary, instead of component counts.
Jira: https://issues.sonatype.org/browse/INT-2832
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/nexus-platform-plugin-feature/job/INT-2832-use-violation-counts/
**Note**: The build on https://ci.jenkins.io will not pass until we release `nexus-java-api`, which will be done shortly after this PR is approved.

Show summary from the policy centric report - INT-2832

---

src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction.groovy
src/main/resources/org/sonatype/nexus/ci/iq/Messages.properties
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthAction/summary.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationProjectAction/jobMain.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthActionTest.groovy

Refined policy evaluation summary section based on product feedback. 
Now it looks like this:
Jira: https://issues.sonatype.org/browse/INT-2832
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/nexus-platform-plugin-feature/job/INT-2832-use-violation-counts-take-2/

Refined policy evaluation summary section, based on product feedback

---

pom.xml
src/main/java/org/sonatype/nexus/ci/config/GlobalNexusConfiguration.groovy
src/main/java/org/sonatype/nexus/ci/config/NxiqConfiguration.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep.groovy
src/main/java/org/sonatype/nexus/ci/nxrm/ComponentUploader.groovy
src/main/java/org/sonatype/nexus/ci/nxrm/v2/ComponentUploaderNxrm2.groovy
src/main/java/org/sonatype/nexus/ci/nxrm/v3/ComponentUploaderNxrm3.groovy
src/main/java/org/sonatype/nexus/ci/util/IqUtil.groovy
src/main/java/org/sonatype/nexus/ci/util/RepositoryManagerClientUtil.groovy

https://issues.sonatype.org/browse/INT-2878
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/nexus-platform-plugin-feature/job/INT-2878-remove-jsr305/build?delay=0sec
Notes
* Once nexus-java-api 3.16 is released we won't need the exclusion there
* The parent drags some in so some overrides are added (without a version) to do the exclusion

INT-2878 Remove jsr305

---

src/main/java/org/sonatype/nexus/ci/config/ComToOrgMigrator.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluator.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptor.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep.groovy
src/main/java/org/sonatype/nexus/ci/util/LoggerBridge.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/Messages.properties
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy

This PR adds a flag that allows users to enable debug logging for the nexus jenkins plugin on a per job basis.
For jobs:
For pipelines:
https://issues.sonatype.org/browse/INT-3615
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/nexus-platform-plugin-feature/job/INT-3615_DebugLoggingFlag/lastBuild/

Added flag to enable per job debug logging INT-1076 INT-3615

---

Jenkinsfile.sonatype
Jenkinsfile.sonatype.extra-tests

https://issues.sonatype.org/browse/INT-4033
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-1918_SupportJava11/lastBuild/
I've also added a new Jenkins job to build feature branches:
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/
which uses a new Jenkins job to run the tests with various Java versions:
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/extra-tests/

Add support for running the test with Java11 in CI builds INT-1918 INT-4033

---

Jenkinsfile.sonatype

Make sure the same binary ends up in Maven Central and Jenkins.io by building the artifact once and pushing it to both destinations.
Jira: https://issues.sonatype.org/browse/INT-3789

INT-3789 - Fix binary inconsistencies between jenkins.io and central

---

Jenkinsfile.sonatype.extra-tests
pom.xml

https://issues.sonatype.org/browse/INT-4078
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-4078_SupportJava14/lastBuild/
I replaced cglib-nodep:3.3.0 with byte-buddy:1.10.18 because cglib-nodep:3.3.0 (latest version) doesn't support Java 14 (only up to Java 13).

Add support for running the tests with Java 14 in CI builds INT-1918 INT-4078

---

pom.xml

Jira: https://issues.sonatype.org/browse/CLM-17707
The fix for the above ticket seems to have been fixed with https://github.com/sonatype/nexus-java-api/pull/151. This is available with java-api 3:26 and I'd like get Jenkins plugin upgraded to this version for testing.

Upgrade to java-api:3.26

---

src/main/java/org/sonatype/nexus/ci/iq/IqClientFactory.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/util/IqUtil.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqClientFactoryTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/util/IqUtilTest.groovy

https://issues.sonatype.org/browse/INT-3589
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-3589-decouple-iq-client/
This update makes `IqClientFactory#getIqClient` enforce that callers of that method provide all of the information that is needed to create an `InternalIQClient` rather than fetching some information from static method on `NxiqConfiguration`. That should make it easier in the future to support multiple IQ servers.
Originally opened as https://github.com/jenkinsci/nexus-platform-plugin/pull/128 but that got stale before being merged.

INT-3589 Decouple IqClientFactory from NxiqConfiguration

---

pom.xml
src/test/java/org/sonatype/nexus/ci/config/ComToOrgMigratorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyEvaluationHealthActionTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyEvaluationReportActionTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/PolicyFailureMessageFormatterTest.groovy

Jira: https://issues.sonatype.org/browse/CLM-18176
Update nexus-platform-api to version 3.34 so the Jenkins plugin supports scanning Java 16 binaries.
Testing locally, the Jenkins plugin processes correctly the binaries.

Update nexus-platform-api 3.34 to support Java 16

---

src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteScanResult.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScanResultTest.groovy

Delete the local copy of the scan file that's created on the master node, so they don't accumulate over time.
JIRA: https://issues.sonatype.org/browse/INT-1446
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-1446-tmp-cleanup/
Demo: link on JIRA ticket

INT-1446 delete temp files from scan after eval

---

docs/overview.md
pom.xml
src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy

The purpose of this PR is to fix a runtime conflict in the plugin.
Conflicting dependencies in Jenkins:
Jenkins provided jar:
```
[INFO] org.sonatype.nexus.ci:nexus-jenkins-plugin:hpi:3.11-SNAPSHOT
[INFO] \- org.jenkins-ci.main:jenkins-core:jar:2.7:provided
[INFO]    \- org.codehaus.woodstox:wstx-asl:jar:3.2.9:provided
```
Bundled with nexus-java-api:
```
[INFO] com.sonatype.insight.scan:insight-scanner-archive:jar:2.29.1-SNAPSHOT
[INFO] \- org.cyclonedx:cyclonedx-core-java:jar:4.1.2:compile
[INFO]    \- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.12.3:compile
[INFO]       \- com.fasterxml.woodstox:woodstox-core:jar:6.2.4:compile
```
Both jars contain similar classes with the same qualified names. The provided jar (which contains older classes) has priority in the class …

Fix runtime error due to stax2 conflict - INT-5253

---

src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy

On scan error count > 0, set build status to `unstable`
Jira: https://issues.sonatype.org/browse/INTC-183
Jenkins: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INTC-183-container-for-jenkins-error/

INTC-183 Make build unstable on scan error count > 0

---

src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy

Fix the assertion in RemoteScannerTest.groovy file. The current statement was missing the `assert` keyword, hence not doing any assertions.

Fix assertion in RemoteScannerTest

---

pom.xml

https://issues.sonatype.org/browse/INT-6159
I'll run a CI build after the nexus-java-api PR is merged to main.

Replaced jaxb with jackson for xml deserialization (to avoid jaxb class loading problems in Jenkins) INT-6159

---

Jenkinsfile.sonatype
pom.xml

https://issues.sonatype.org/browse/INT-6112
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6112_UseClmMavenPlugin/
I enabled clm-maven-plugin to get a more accurate BOM (instead of scanning the binary).

Use clm-maven-plugin INT-6112

---

README.md

Updating release notes for release `3.11.20210420-142258.bdfc332`. Adding note for Nuget scanning bug fix.
JIRA: https://issues.sonatype.org/browse/INT-5615
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-5615-updating-release-notes-for-nuget-bug/

INT-5615 Updating release notes

---

src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy

https://issues.sonatype.org/browse/INTC-375
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INTC-375_Ensure_IaC_scans_are_supported_in_the_Jenkins_plugin/
Demo: https://drive.google.com/file/d/1AMAaWuium-bKLOOlmdMxNVbDYUJxP4AF/view?usp=sharing

INTC-375 - Ensure IaC scans are supported in the Jenkins plugin

---

pom.xml

The purpose of this change is to switch the log entries like "...Finished scanning target: ..." from INFO to DEBUG level. 
This is a draft PR just to prove that all tests pass. After approval I intend to release `nexus-java-api` and update its version here, so the testing is done against the release version.
Jira: https://issues.sonatype.org/browse/INT-6005
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6005-logging-tweak/

Tweak repetitive logging - INT-6005

---

Jenkinsfile.sonatype.bump-up-api
Jenkinsfile.sonatype.release

In this PR we are using a shared library to update the release notes. We are also adding a new boolean parameter to determine if we want to add to the release notes a link to IQ release notes.
The function used to update the release notes is part of this other PR: https://github.com/sonatype/int-jenkins-shared/pull/12
JIRA: https://issues.sonatype.org/browse/INT-6477
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6477-adjusting-jenkins-release-script/

INT-6477 Using shared library to update the release notes

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/IqClientFactory.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/main/java/org/sonatype/nexus/ci/util/ProxyUtil.groovy
src/main/java/org/sonatype/nexus/ci/util/RepositoryManagerClientUtil.groovy
src/test/java/org/sonatype/nexus/ci/util/ProxyUtilTest.groovy

Delegating no proxy hosts validation to `NXRM` and `IQ` HTTP client builders. This change is complemented with the next PR: https://github.com/sonatype/nexus-java-api/pull/201
After this change:
* IQ client and NXRM client will behave consistently with the Proxy setup. 
* Both of them will support JVM setup
```bash
-Dhttp.proxyHost=127.0.0.1 
-Dhttp.proxyPort=8080
-Dhttp.nonProxyHosts="*.demo" 
```
* Both of them will support proxy setup through the **Manage Jenkins > Manage Plugins > Advanced** tab 
* If **JVM** and **Advanced** tab are both configured, then the plugin will take the configuration from *Jenkins*
JIRA: https://issues.sonatype.org/browse/INT-6770
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6770-adjust-no-proxy-hosts-valid …

INT-6770 Adjusting no proxy hosts validation

---

support/README.md
support/print-plugins-information-script.groovy

Adding a script to get information about the plugins installed on the Jenkins server. It gets information about the plugins, the loaded packages by each plugin, and how Jenkins is loading some classes.
As we haven't been able to reproduce the issue reported on the JIRA ticket, we are creating this script to try to get a picture of the customer's Jenkins server to try to reproduce the issue locally.
JIRA: https://issues.sonatype.org/browse/INT-6741
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6741-support-script-to-get-plugin-details/

INT-6741 Create support script to get plugins details

---

Jenkinsfile.sonatype
Jenkinsfile.sonatype.post-release

In this PR:
- Added policy evaluation step for the release stage (in the post-release script). Even though it's late in the release flow, it is still useful for continuous monitoring.
- Added Slack notifications for the main release and snapshot builds
Jira: https://issues.sonatype.org/browse/INT-6510
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-6510_CI_Improvements/

CI improvements - INT-6510

---

Jenkinsfile.sonatype.extra-tests

Adding tests for Jenkins  2.346.2
Jira: https://issues.sonatype.org/browse/INT-7002
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7002-check-compatibility-with-jenkins-2.346.2/

INT-7002 Check compatibility with Jenkins 2.346.2

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluator.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptor.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/help-iqOrganization.html
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep/help-iqOrganization.html
src/main/resources/org/sonatype/nexus/ci/iq/Messages.properties
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorDescriptorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorSlaveIntegrationTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy

Adding support to add Organization Id as an optional parameter for nexus IQ policy evaluation
JIRA: https://issues.sonatype.org/browse/INT-7157
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7157-add-org-id-param-to-pipeline-syntax/

INT-7157 add org id parameter to nexus IQ policy evaluation pipeline syntax

---

src/main/java/org/sonatype/nexus/ci/iq/PolicyEvaluationReportUtil.groovy
src/main/resources/org/sonatype/nexus/ci/iq/PolicyEvaluationReportAction/index.jelly
src/test/java/org/sonatype/nexus/ci/iq/PolicyEvaluationReportActionTest.groovy

Fixing build report to show notify actions with proper icon and ensure they are not counted as failure actions
JIRA: https://issues.sonatype.org/browse/INT-7228
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7228-fixing-build-report-for-notify-actions/
Screenshot
-------------
This is how the new icon for the Notify action is displayed

INT-7228 Fixing build report for notify actions

---

pom.xml

Jenkins plugin was resolving the wrong dependency for ANTLR. With this change, we ensure our plugin looks for the right dependency on the bundled libraries.
JIRA: https://issues.sonatype.org/browse/INT-7295
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7295-solving-antlr-version-mismatch/

INT-7295 Solving ANTLR version mismatch

---

Jenkinsfile.sonatype.extra-tests

**Links**
Jira: https://issues.sonatype.org/browse/INT-7476
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7476_Check_compatibility_Jenkins_2.361.4/

INT-7476 Check compatibility with Jenkins version 2.361.4

---

src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorBuildStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorWorkflowStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/nxrm/NexusPublisherBuildStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/nxrm/NexusPublisherWorkflowStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/nxrm/v3/AssociateTagStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/nxrm/v3/CreateTagStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/nxrm/v3/DeleteComponentsStep/config.groovy
src/main/resources/org/sonatype/nexus/ci/nxrm/v3/MoveComponentsStep/config.groovy

In 2.401, we have removed `l:css` from core, when we dropped the dependency on `jenkins-js-modules`. Therefore, `l.css`, the groovy equivalent, is gone too, but it appears the only two plugins using groovy views and `l.css` weren't updated.
Hence, I'm filing this PR retrospectively.
In groovy, `link` is equal to the HTML tag `<link>`, this PR makes use of, working independently of Jenkins versions.

Adapt 'l.css' removal in Jenkins 2.401 onwards

---

Jenkinsfile.sonatype.extra-tests
src/test/java/org/sonatype/nexus/ci/iq/PipelineSyntaxIntegrationTest.groovy

JenkinsCI version 2.414.1
Ref: CLM-27258
Jenkins https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-27258/
Jira https://sonatype.atlassian.net/browse/CLM-27258
This PR replaces https://github.com/jenkinsci/nexus-platform-plugin/pull/281

CLM-27258: Updated the latest version of JenkinsCI 2.414.1 to be tested with Java 17

---

pom.xml
src/main/java/org/sonatype/nexus/ci/config/NxiqConfiguration.groovy
src/main/java/org/sonatype/nexus/ci/config/Nxrm2Configuration.groovy
src/main/java/org/sonatype/nexus/ci/config/Nxrm3Configuration.groovy

Nexus Platform plugin does not perform permission checks allowing user with Overall/Read permission to connect to an attacker-specified URL.
Two of the three endpoints also lead to a Credentials leaking due to the presence of the `credentialsId `parameter which can be used by an attacker to receive a request with username and password base64 encoded inside the headers as Basic Authentication.
Additionally, these HTTP endpoints do not require POST request, resulting in a cross-site request forgery (CSRF) vulnerability.
Culprit
[NxiqConfiguration.groovy#L126](https://github.com/jenkinsci/nexus-platform-plugin/blob/ba7b10f1c4cf3a712d2836ad66f5ed0d2047ad49/src/main/java/org/sonatype/nexus/ci/config/NxiqConfiguration.groovy#L126)
[Nxrm2Configuration.groovy#L61](https://github.com/jenkinsci/nexu …

 Add protection from CSRF

---

Jenkinsfile.sonatype.extra-tests
pom.xml
src/test/java/org/sonatype/nexus/ci/iq/PipelineSyntaxIntegrationTest.groovy

I also manually tested by running Jenkins Version 2.426.1 locally and installing the snapshot hpi.. I verified running a pipeline completed successfully.. 
https://sonatype.atlassian.net/browse/CLM-28551
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-28551_Check_Jenkins_plugin_compatibility_with_Jenkins_version_2.426.1/

CLM-28551 - Check Jenkins plugin compatibility with Jenkins version 2.426.1

---

pom.xml
src/main/java/org/sonatype/nexus/ci/config/GlobalNexusConfiguration.groovy
src/test/java/org/sonatype/nexus/ci/config/GlobalNexusConfigurationTest.groovy

https://sonatype.atlassian.net/browse/CLM-28746
https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-28746_Use_Jenkins_Instance_Id_For_Telemetry/
When there are multiple instances of IQ is configured in Jenkins, there is still one `instanceId`. See below the configuration file found in `.jenkins` folder. The `instanceId` being used is: `c9765940a54f41b98c98eb8aab5e264f`. 
```
<?xml version='1.1' encoding='UTF-8'?>
<org.sonatype.nexus.ci.config.GlobalNexusConfiguration plugin="nexus-jenkins-plugin@3.19.1-SNAPSHOT">
<nxrmConfigs/>
<iqConfigs>
<org.sonatype.nexus.ci.config.NxiqConfiguration>
<id>nexusiq</id>
<internalId>3735cfdb-6d66-4d98-9cc3-d26f142e8c05</internalId>
</org.sonatype.nexus.ci.config.NxiqConfiguration> …
```

CLM-28746 - Use Jenkins InstanceId For Telemetry

---

src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy

Jira ticket: https://sonatype.atlassian.net/browse/INT-7963
CI: https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/INT-7963_Exclude_Scan_Patterns_doesnt_work/lastBuild/
The purpose of this PR is to add a fix for the use of file exclusion patterns. The files to exclude are passed as parameters with a "!" at the beginning. 
For example:
Example 1: 
```
stage('build') {
nexusPolicyEvaluation iqStage: 'build', iqApplication: 'app',
iqScanPatterns: [[scanPattern: '**'], [scanPattern: '!*.zip']]
failBuildOnNetworkError: true
}
```
Example 2:
```[tasklist]
```

INT-7963 - [FIX] Exclude Scan Patterns does not exclude correctly

---

pom.xml
src/main/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorUtil.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteFileResolver.groovy
src/main/java/org/sonatype/nexus/ci/iq/RemoteScanner.groovy
src/main/java/org/sonatype/nexus/ci/iq/ScanPatternUtil.groovy
src/test/java/org/sonatype/nexus/ci/iq/IqPolicyEvaluatorTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/RemoteScannerTest.groovy
src/test/java/org/sonatype/nexus/ci/iq/ScanPatternUtilTest.groovy

https://sonatype.atlassian.net/browse/SDEV-1117
For callflow we will either reuse the scan patterns provied for the traditional scan or alternatively make use of an ovveride. In either case before hadning off to dependencies to do the actual work the patterns need to be resolved to file targets.
Because jenkins manages a cluster this needs to be done from the right context. I have refactored out the actuall file resolution logic to make it easier to re-use and created a new class that extends MasterToSlaveCallable so that we can leverage the logic from the right place.
The orginal place where this logic was used inside RemoteScanner was already within a MasterToSlaveCallable class, so nothin needed to change there, other than pointing to the logics new location.
Some tests were refactored …

SDEV-1117: Make sure target resolution always happens from within an MasterToSlaveCallable
